apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.platform.adhar.io
spec:
  claimNames:
    kind: Cluster
    plural: clusters
  group: platform.adhar.io
  names:
    categories:
    - crossplane
    kind: XCluster
    plural: xclusters
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Cluster is the Schema for the Cluster API.
        properties:
          spec:
            description: ClusterSpec defines the desired state of Cluster.
            type: object
          status:
            description: ClusterStatus defines the observed state of Cluster.
            type: object
        required:
        - spec
        type: object
    served: true
